liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # define your filter sets under this option
    filter_sets:

        my_heighten_filter:
            format: jpeg
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 60
        my_widen_filter:
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                    # given 50x40px, output 32x26px using "widen" option
                    widen: 32
        my_increase_filter:
            format: jpeg
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                    # given 50x40px, output 60x50px, using "increase" option
                    increase: 0
        my_scale_filter:
            format: jpeg
            filters:
                relative_resize:
                    scale: 1

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail:

            # set your image quality defaults
            format: jpeg
            jpeg_quality:          85
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [253, 253]
                    mode:          outbound
                    allow_upscale: true

                # create border by placing image on larger black background
                background:
                    size:     [256, 256]
                    position: center
                    color:    '#fff'
