#
security:

    providers:
        auth_token_provider:
            id: routanglangquanbundle.auth_token_provider

    encoders:
        App\Entity\Association\RtlqAdherent:
            algorithm: bcrypt
            cost: 12

    firewalls:
        debug:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            #pattern: ^/
            security: false

        public_photos_api:
            pattern: ^/association/photo
            methods: [GET]
            anonymous: ~

        public_cotisations_active_api:
            pattern: ^/cotisations/active
            methods: [GET]
            anonymous: ~

        public_saisons_active_api:
            pattern: ^/saisons/active
            methods: [GET]
            anonymous: ~

        public_news_api:
            pattern: ^/association/news
            methods: [GET]
            anonymous: ~

        public_technique_api:
            pattern: ^/technique/setup
            methods: [GET]
            anonymous: ~
        
        public_login_api:
            pattern: ^/security/tokens
            methods: [POST]
            anonymous: ~

        public_reset_password_api:
            pattern: ^/association/adherents/password-reset
            methods: [POST]
            anonymous: ~
        public_change_password_api:
            pattern: ^/association/adherents/password-change
            methods: [POST]
            anonymous: ~
        
        internal_api:
            pattern: ^/
            methods: [GET, PUT, DELETE, POST, OPTIONS]
            stateless: true
            simple_preauth:
                authenticator: routanglangquanbundle.auth_token_authenticator
            provider: auth_token_provider
            anonymous: ~

    access_control:
        - { path: ^/association/adherents/password-change,  methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/adherents/password-reset,  methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/photo_directories, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cotisations/active, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saisons/active, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/news, methods: [GET] ,roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/technique/setup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/tokens, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/photos, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/security/tokens/check-user, methods: [GET, OPTIONS], roles: ROLE_USER }
        - { path: ^/association/adherents/trombinoscope, methods: [GET, OPTIONS], roles: ROLE_USER }
        - { path: ^/association/adherents/by-token, methods: [GET, OPTIONS, PUT], roles: ROLE_USER }
        - { path: ^/association/drive/by-token, methods: [GET, OPTIONS], roles: ROLE_USER }
        
        - { path: ^/kpis, roles: ROLE_KPI }

        - { path: ^/association/photo_directories, methods: [DELETE, PUT, POST, OPTIONS], roles: ROLE_COM }
        - { path: ^/association/photos, methods: [DELETE, PUT, POST, OPTIONS], roles: ROLE_COM }
        - { path: ^/association/news, methods: [DELETE, PUT, POST, OPTIONS], roles: [ROLE_COM] }

        - { path: ^/association/events, methods: [GET, DELETE, PUT, POST, OPTIONS], roles: [ROLE_BEN] }
        - { path: ^/association/benevolats, methods: [GET, DELETE, PUT, POST, OPTIONS], roles: [ROLE_BEN] }

        - { path: ^/saisons, methods: [GET, OPTIONS], roles: [ROLE_BEN, ROLE_TRE] }
        - { path: ^/tresorie/categories, methods: [GET, OPTIONS], roles: [ROLE_BEN, ROLE_TRE] }
        - { path: ^/association/adherents/liste, methods: [GET, OPTIONS], roles: [ROLE_BEN, ROLE_TRE] }

        - { path: ^/cotisations, methods: [GET, DELETE, PUT, POST, OPTIONS], roles: [ROLE_TRE] }
        - { path: ^/materiels, roles: ROLE_TRE }

        - { path: ^/, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_COM:         [ROLE_COM]
        ROLE_PROF:        [ROLE_PROF]
        ROLE_TRE:         [ROLE_TRE]
        ROLE_KPI:         [ROLE_KPI]
        ROLE_ADMIN:       [ROLE_KPI, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PROF, ROLE_KPI, ROLE_TRE, ROLE_COM, ROLE_ADMIN, ROLE_SUPER_ADMIN]