#
security:

    providers:
        auth_token_provider:
            id: routanglangquanbundle.auth_token_provider

    encoders:
        App\Entity\Association\RtlqAdherent:
            algorithm: bcrypt
            cost: 12

    firewalls:
        debug:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            #pattern: ^/
            security: false

        public_photos_api:
            pattern: ^/association/photo
            methods: [GET]
            anonymous: ~

        public_cotisations_active_api:
            pattern: ^/cotisations/active
            methods: [GET]
            anonymous: ~

        public_saisons_active_api:
            pattern: ^/saisons/active
            methods: [GET]
            anonymous: ~

        public_news_api:
            pattern: ^/association/news
            methods: [GET]
            anonymous: ~

        public_technique_api:
            pattern: ^/technique/setup
            methods: [GET]
            anonymous: ~
        
        public_login_api:
            pattern: ^/security/tokens
            methods: [POST]
            anonymous: ~

        public_reset_password_api:
            pattern: ^/association/adherents/password-*
            methods: [POST]
            anonymous: ~

        internal_api:
            pattern: ^/
            methods: [GET, PUT, DELETE, POST, OPTIONS]
            stateless: true
            simple_preauth:
                authenticator: routanglangquanbundle.auth_token_authenticator
            provider: auth_token_provider
            anonymous: ~

    access_control:
        - { path: ^/association/photo_directories, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/photo_directories, methods: [DELETE, PUT, POST, OPTIONS], roles: ROLE_COM }
        - { path: ^/association/photos, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/photos, methods: [DELETE, PUT, POST, OPTIONS], roles: ROLE_COM }
        - { path: ^/association/events, methods: [GET, DELETE, PUT, POST, OPTIONS], roles: [ROLE_ADMIN, ROLE_BEN] }
        - { path: ^/association/adherents, roles: ROLE_ADMIN }
        - { path: ^/association, methods: [DELETE, PUT, POST, OPTIONS], roles: ROLE_ADMIN }
        - { path: ^/kpis, roles: ROLE_KPI }
        - { path: ^/cotisations/active, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cotisations, methods: [GET, DELETE, PUT, POST, OPTIONS], roles: [ROLE_TRE] }
        - { path: ^/saisons/active, methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saisons, methods: [DELETE, PUT, POST, OPTIONS], roles: [ROLE_ADMIN] }
        - { path: ^/association/news, methods: [GET] ,roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/news, methods: [DELETE, PUT, POST, OPTIONS], roles: [ROLE_COM] }
        - { path: ^/technique/setup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/tokens, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/adherents/password-*,  methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/groupes, roles: ROLE_ADMIN }
        - { path: ^/association/kungfu, roles: ROLE_ADMIN }
        - { path: ^/materiels, roles: ROLE_TRE }
        - { path: ^/saisons, roles: ROLE_ADMIN }
        - { path: ^/tresorie/categories, roles: ROLE_ADMIN }
        - { path: ^/tresorie/tresories, roles: ROLE_ADMIN }
        - { path: ^/tresorie/etats, roles: ROLE_ADMIN }
        - { path: ^/kungfu/styles, roles: ROLE_ADMIN }
        - { path: ^/kungfu/niveaux, roles: ROLE_ADMIN }
        - { path: ^/kungfu/taos, roles: ROLE_PROF }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_COM:         [ROLE_COM]
        ROLE_PROF:        [ROLE_PROF]
        ROLE_TRE:         [ROLE_TRE]
        ROLE_KPI:         [ROLE_KPI]
        ROLE_ADMIN:       [ROLE_KPI, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PROF, ROLE_KPI, ROLE_TRE, ROLE_COM, ROLE_ADMIN, ROLE_SUPER_ADMIN]