swiftmailer:
    spool: { type: 'memory' }
    transport: gmail
    encryption: ssl
    host: smtp.googlemail.com
    port: 465
    auth_mode: login
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PWD)%'
