# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        auth_token_provider:
            id: routanglangquanbundle.auth_token_provider

    encoders:
        RoutanglangquanBundle\Entity\Association\RtlqAdherent:
            algorithm: bcrypt
            cost: 12

    firewalls:
        debug:
            pattern: ^/(_(profiler|wdt)|css|images|js|api)/
            security: false
        main:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: routanglangquanbundle.auth_token_authenticator
            provider: auth_token_provider
            anonymous: ~

    access_control:
        - { path: ^/api, roles: ROLE_ADMIN }
        

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN]
