# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        auth_token_provider:
            id: routanglangquanbundle.auth_token_provider

    encoders:
        RoutanglangquanBundle\Entity\Association\RtlqAdherent:
            algorithm: bcrypt
            cost: 12

    firewalls:
        debug:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public_photo_api:
            pattern: ^/api/association/photo
            methods: [GET]
            anonymous: ~

        internal_api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: routanglangquanbundle.auth_token_authenticator
            provider: auth_token_provider
            anonymous: ~

    access_control:
        - { path: ^/api/association/photo_directories, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/association/photos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        
        

    role_hierarchy:
        ROLE_ANONYMOUS:   [ROLE_USER]
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN]
