parameters:
    rss:
        author: KFR
        description: Suivez l'actualité de notre association sur le notre site https://kungfurennes.fr
        url: https://kungfurennes.fr
        title: KFR - A la Une
        image_url: https://kungfurennes.fr/presentation/html5/img/association/logo-200.png
        email: kungfurennes@gmail.com


