
security:
    providers:
        auth_token_provider:
            id: routanglangquanbundle.auth_token_provider

    encoders:
        RoutanglangquanBundle\Entity\Association\RtlqAdherent:
            algorithm: bcrypt
            cost: 12

    firewalls:
        debug:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            pattern: ^/
            security: false

        public_photos_api:
            pattern: ^/association/photo
            methods: [GET]
            anonymous: ~

        public_cotisations_active_api:
            pattern: ^/cotisations/active
            methods: [GET]
            anonymous: ~

        public_saisons_active_api:
            pattern: ^/saisons/active
            methods: [GET]
            anonymous: ~

        public_news_api:
            pattern: ^/association/news
            methods: [GET]
            anonymous: ~

        public_technique_api:
            pattern: ^/technique/setup
            methods: [GET]
            anonymous: ~

        internal_api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: routanglangquanbundle.auth_token_authenticator
            provider: auth_token_provider
            anonymous: ~


    access_control:
        - { path: ^/association/photo_directories, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/photos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cotisations/active, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saisons/active, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/association/news, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/technique/setup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        
        

    role_hierarchy:
        ROLE_ANONYMOUS:   [ROLE_USER]
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN]
