services:

    routanglangquanbundle.auth_token_provider:
        class: RoutanglangquanBundle\Service\Security\User\AuthTokenUserProvider
        arguments: 
            - "@=service('doctrine.orm.entity_manager').getRepository('RoutanglangquanBundle:Security\\\\RtlqAuthToken')"
            - "@=service('doctrine.orm.entity_manager').getRepository('RoutanglangquanBundle:Association\\\\RtlqAdherent')"

    routanglangquanbundle.auth_token_authenticator:
        class: RoutanglangquanBundle\Service\Security\User\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
